# Enclypt 2.0 Configuration File

[general]
key_directory = "~/.enclypt2/keys"
default_chunk_size = 1048576  # 1MB
max_file_size = 10737418240   # 10GB
enable_compression = false

[server]
default_port = 8080
default_host = "127.0.0.1"
max_upload_size = 104857600   # 100MB
enable_cors = false
require_api_key = false

[logging]
level = "info"
format = "compact"
log_to_file = false
log_file = "logs/enclypt2.log"
